#!/bin/sh /etc/rc.common
START=50
STOP=50
USE_PROCD=1
config_load bd_fan
start_service() {
    config_get enable main enable
    if [ "$enable" = "0" ]; then
        disable_fan
    else
        enable_fan
    fi
}

stop_service() {
    echo do nothing
}

disable_fan() {
    echo 1000 > /sys/class/thermal/thermal_zone0/emul_temp
    echo disabled > /sys/class/thermal/thermal_zone0/mode
    echo 0 > /sys/class/thermal/thermal_zone0/emul_temp
}

enable_fan() {
    echo 1000 > /sys/class/thermal/thermal_zone0/emul_temp
    echo enabled > /sys/class/thermal/thermal_zone0/mode
    echo 0 > /sys/class/thermal/thermal_zone0/emul_temp
}

reload_service() {
    stop
    start
}

service_triggers() {
	procd_add_reload_trigger 'bd_fan'
}
